from __future__ import annotations
"""
eurovision_train.py

Trains and evaluates models with GroupKFold by 'year'. Uses the label and top_k
stored in the meta generated by preprocessing, unless you explicitly pass a different
--top-k here (in which case the label is recomputed on-the-fly for training only).

Outputs
-------
- cv_predictions.csv : ONE row per (song, fold) with columns:
    year, country, song, artist, place, y_true, proba_<model>..., fold
- cv_metrics.json    : per-fold and aggregate metrics (AUROC, AP, F1@0.5, Hits@K)
- final models (.joblib)           [optional, with --fit-final]
- ensemble.json (definition)       [optional, with --fit-final and multiple models]
"""

import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd
from scipy import sparse
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import average_precision_score, f1_score, roc_auc_score
from sklearn.model_selection import GroupKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MaxAbsScaler, OneHotEncoder


# -----------------------
# I/O
# -----------------------
def load_data(parquet_path: Path, meta_path: Path) -> Tuple[pd.DataFrame, Dict]:
    """Load cleaned Parquet and meta JSON."""
    df = pd.read_parquet(parquet_path)
    with open(meta_path, "r", encoding="utf-8") as f:
        meta = json.load(f)
    for r in ["numeric_features", "categorical_features"]:
        if r not in meta:
            raise KeyError(f"Missing '{r}' in features meta JSON.")
    if "year" not in df.columns:
        raise KeyError("Expected a 'year' column for GroupKFold.")
    return df, meta


# -----------------------
# Label & groups
# -----------------------
def build_X_y_groups(
    df: pd.DataFrame,
    meta: Dict,
    top_k_override: Optional[int] = None
) -> Tuple[pd.DataFrame, pd.Series, np.ndarray, pd.DataFrame, int]:
    """
    Create X (DataFrame), y (Series), groups (year), ids, and the K used.
    If top_k_override is provided, compute y = 1[place <= K] here. Otherwise use meta['label'].
    """
    if top_k_override is not None:
        if "place" not in df.columns:
            raise KeyError("Requested --top-k but 'place' column is missing.")
        place = pd.to_numeric(df["place"], errors="coerce")
        y = (place.notna() & (place <= top_k_override)).astype(int)
        used_k = int(top_k_override)
    else:
        label_col = meta.get("label")
        if not label_col or label_col not in df.columns:
            raise KeyError("No --top-k given and meta['label'] not found in data.")
        y = df[label_col].astype(int)
        used_k = int(meta.get("top_k", 3))

    groups = df["year"].to_numpy()
    id_cols = [c for c in ["year", "country", "song", "artist", "place"] if c in df.columns]
    ids = df[id_cols].copy() if id_cols else pd.DataFrame(index=df.index)
    X = df.copy()
    print(f"[info] Using Top{used_k} label for training/evaluation")
    return X, y, groups, ids, used_k


# -----------------------
# Pipelines
# -----------------------
def _to_sparse(X):
    """Convert dense array to CSR sparse for MaxAbsScaler (sparse-friendly)."""
    return sparse.csr_matrix(X)

def build_column_transformer(
    numeric_features: List[str],
    categorical_features: List[str],
    text_feature: Optional[str] = None,
    tfidf_max_features: int = 10000,
) -> ColumnTransformer:
    """Sparse ColumnTransformer for LR pipeline (numeric + categorical + optional TF-IDF)."""
    from sklearn.preprocessing import FunctionTransformer
    num_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("to_sparse", FunctionTransformer(_to_sparse, accept_sparse=True)),
        ("scale", MaxAbsScaler()),
    ])
    cat_pipe = OneHotEncoder(handle_unknown="ignore")  # sparse by default
    transformers = [("num", num_pipe, numeric_features), ("cat", cat_pipe, categorical_features)]
    if text_feature:
        transformers.append(("text", TfidfVectorizer(
            ngram_range=(1, 2), min_df=3, max_df=0.6,
            max_features=tfidf_max_features, sublinear_tf=True, norm="l2"
        ), text_feature))
    return ColumnTransformer(transformers=transformers, remainder="drop", sparse_threshold=1.0)

def build_lr_pipeline(
    numeric_features: List[str],
    categorical_features: List[str],
    text_feature: Optional[str],
    C: float = 1.0,
    penalty: str = "l2",
    l1_ratio: Optional[float] = None,
    tfidf_max_features: int = 10000,
) -> Pipeline:
    """Logistic Regression on sparse text+tabular input."""
    ct = build_column_transformer(numeric_features, categorical_features, text_feature, tfidf_max_features)
    lr = LogisticRegression(
        solver="saga", C=C, penalty=penalty, l1_ratio=l1_ratio,
        max_iter=5000, class_weight="balanced"
    )
    return Pipeline([("features", ct), ("clf", lr)])

def build_hgb_pipeline(numeric_features: List[str], categorical_features: List[str]) -> Pipeline:
    """HistGradientBoosting on dense tabular (no TF-IDF)."""
    try:
        ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    except TypeError:
        ohe = OneHotEncoder(handle_unknown="ignore", sparse=False)

    ct = ColumnTransformer(
        transformers=[
            ("num", SimpleImputer(strategy="median"), numeric_features),
            ("cat", ohe, categorical_features),
        ],
        remainder="drop",
        sparse_threshold=0.0,  # force dense
    )
    hgb = HistGradientBoostingClassifier(
        learning_rate=0.08, max_depth=None, max_leaf_nodes=31,
        l2_regularization=0.0, random_state=42
    )
    from sklearn.preprocessing import FunctionTransformer
    to_float32 = FunctionTransformer(lambda X: np.asarray(X, dtype=np.float32), accept_sparse=False)
    return Pipeline([
        ("features", ct),
        ("clf", hgb),
    ])


# -----------------------
# Metrics & CV
# -----------------------
def compute_balanced_sample_weights(y: np.ndarray) -> np.ndarray:
    """Weights equivalent to class_weight='balanced' for estimators that don't support it (HGB)."""
    from sklearn.utils.class_weight import compute_class_weight
    classes = np.array([0, 1])
    class_w = compute_class_weight(class_weight="balanced", classes=classes, y=y)
    w = np.ones_like(y, dtype=float)
    for c, cw in zip(classes, class_w):
        w[y == c] = cw
    return w

def hits_at_k_per_year(y_true: np.ndarray, y_proba: np.ndarray, years: np.ndarray, k: int) -> Tuple[float, pd.DataFrame]:
    """For each year, take top-K by predicted probability and count true positives; return mean and per-year table."""
    df = pd.DataFrame({"year": years, "y_true": y_true, "proba": y_proba})
    per_year = []
    for yr, grp in df.groupby("year"):
        grp = grp.sort_values("proba", ascending=False)
        kk = min(int(k), len(grp))
        hits = grp.head(kk)["y_true"].sum()
        per_year.append({"year": int(yr), "hits": int(hits), "k": int(kk)})
    per_year_df = pd.DataFrame(per_year).sort_values("year")
    mean_hits = per_year_df["hits"].mean() if len(per_year_df) else 0.0
    return mean_hits, per_year_df

def evaluate_models_cv(
    X: pd.DataFrame,
    y: pd.Series,
    groups: np.ndarray,
    ids: pd.DataFrame,
    pipelines: Dict[str, Pipeline],
    n_splits: int,
    hits_k: int,
    ensemble: bool,
    out_dir: Optional[Path],
) -> Dict:
    """Run GroupKFold by 'year', evaluate all requested pipelines, and save predictions/metrics."""
    years_unique = np.unique(groups)
    n_splits = min(n_splits, len(years_unique))
    gkf = GroupKFold(n_splits=n_splits)

    all_rows = []
    metrics_summary: Dict[Tuple[str, str, int], Dict] = {}
    fold_idx = 0

    for train_idx, test_idx in gkf.split(X, y, groups):
        fold_idx += 1
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx].to_numpy(), y.iloc[test_idx].to_numpy()
        groups_test = groups[test_idx]
        ids_test = ids.iloc[test_idx].reset_index(drop=True)

        sample_weight = compute_balanced_sample_weights(y_train)

        fold_probas: Dict[str, np.ndarray] = {}
        for name, pipe in pipelines.items():
            if isinstance(pipe.named_steps["clf"], HistGradientBoostingClassifier):
                pipe.fit(X_train, y_train, clf__sample_weight=sample_weight)
            else:
                pipe.fit(X_train, y_train)
            fold_probas[name] = pipe.predict_proba(X_test)[:, 1]

        if ensemble and len(fold_probas) >= 2:
            ens_proba = np.mean(np.vstack(list(fold_probas.values())), axis=0)
            fold_probas["ensemble"] = ens_proba

        # Per-model metrics
        for name, proba in fold_probas.items():
            try:
                auroc = roc_auc_score(y_test, proba)
            except ValueError:
                auroc = np.nan
            ap = average_precision_score(y_test, proba)
            y_pred = (proba >= 0.5).astype(int)
            f1p = f1_score(y_test, y_pred, pos_label=1)
            hits_mean, _ = hits_at_k_per_year(y_test, proba, groups_test, k=hits_k)
            metrics_summary[(name, "fold", fold_idx)] = {
                "AUROC": float(auroc),
                "AP": float(ap),
                "F1_pos": float(f1p),
                f"Hits@{hits_k}_mean": float(hits_mean),
                "n_test": int(len(y_test)),
            }

        # One wide row per song with all probabilities
        fold_df = ids_test.copy()
        fold_df["y_true"] = y_test
        for name, proba in fold_probas.items():
            fold_df[f"proba_{name}"] = proba
        fold_df["fold"] = fold_idx
        all_rows.append(fold_df)

    preds = pd.concat(all_rows, axis=0).reset_index(drop=True)

    # Aggregate across folds
    models_in_run = sorted({k[0] for k in metrics_summary.keys()})
    agg = {}
    for name in models_in_run:
        rows = [v for (m, _, _), v in metrics_summary.items() if m == name]
        agg[name] = {
            "AUROC_mean": float(np.nanmean([r["AUROC"] for r in rows])),
            "AP_mean": float(np.mean([r["AP"] for r in rows])),
            "F1_pos_mean": float(np.mean([r["F1_pos"] for r in rows])),
            f"Hits@{hits_k}_mean": float(np.mean([r[f"Hits@{hits_k}_mean"] for r in rows])),
            "folds": len(rows),
        }

    if out_dir:
        out_dir.mkdir(parents=True, exist_ok=True)
        preds.to_csv(out_dir / "cv_predictions.csv", index=False)
        with open(out_dir / "cv_metrics.json", "w", encoding="utf-8") as f:
            json.dump(
                {"per_fold": {str(k): v for k, v in metrics_summary.items()}, "aggregate": agg},
                f, indent=2
            )
    return {"preds": preds, "metrics_per_fold": metrics_summary, "metrics_agg": agg}


# -----------------------
# Fit-final (optional)
# -----------------------
def fit_and_save_final(
    X: pd.DataFrame, y: pd.Series, pipelines: Dict[str, Pipeline], out_dir: Path, ensemble: bool
):
    """Fit pipelines on ALL data and save .joblib (and ensemble definition if applicable)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, pipe in pipelines.items():
        pipe.fit(X, y)
        joblib.dump(pipe, out_dir / f"{name}.joblib")
    if ensemble and len(pipelines) >= 2:
        with open(out_dir / "ensemble.json", "w", encoding="utf-8") as f:
            json.dump({"type": "mean", "models": list(pipelines.keys())}, f, indent=2)


# -----------------------
# CLI
# -----------------------
def main():
    import argparse
    p = argparse.ArgumentParser(description="Train & evaluate Eurovision models with year-grouped CV.")
    p.add_argument("--data", type=Path, default=Path("datasets/esc_clean.parquet"))
    p.add_argument("--meta", type=Path, default=Path("datasets/esc_features_meta.json"))
    p.add_argument("--cv-splits", type=int, default=5)
    p.add_argument("--tfidf-max-features", type=int, default=10000)
    p.add_argument("--out-dir", type=Path, default=Path("artifacts"))
    p.add_argument("--run", choices=["lr", "hgb", "both"], default="both")
    p.add_argument("--ensemble", action="store_true", default=True)
    p.add_argument("--fit-final", action="store_true")
    p.add_argument("--top-k", type=int, default=None,
                   help="If provided, recompute label as 1[place<=K] and evaluate Hits@K; "
                        "else use meta['label'] and meta['top_k'].")
    args = p.parse_args()

    df, meta = load_data(args.data, args.meta)
    X, y, groups, ids, used_k = build_X_y_groups(df, meta, top_k_override=args.top_k)

    num_features = meta["numeric_features"]
    cat_features = meta["categorical_features"]
    text_feature = meta.get("text_feature")

    pipelines: Dict[str, Pipeline] = {}
    if args.run in ("lr", "both"):
        pipelines["lr_text_tab"] = build_lr_pipeline(
            num_features, cat_features, text_feature, tfidf_max_features=args.tfidf_max_features
        )
    if args.run in ("hgb", "both"):
        pipelines["hgb_tabular"] = build_hgb_pipeline(num_features, cat_features)

    results = evaluate_models_cv(
        X, y, groups, ids, pipelines,
        n_splits=args.cv_splits, hits_k=used_k,
        ensemble=args.ensemble, out_dir=args.out_dir
    )

    print("\n=== Aggregate CV metrics ===")
    for name, m in results["metrics_agg"].items():
        print(
            f"{name:12s}  AUROC={m['AUROC_mean']:.3f} | AP={m['AP_mean']:.3f} | "
            f"F1+= {m['F1_pos_mean']:.3f} | Hits@{used_k}={m[f'Hits@{used_k}_mean']:.2f} "
            f"(folds={m['folds']})"
        )

    if args.fit_final:
        fit_and_save_final(X, y, pipelines, args.out_dir, ensemble=args.ensemble)
        print(f"\nSaved final model(s) to: {args.out_dir.resolve()}")

if __name__ == "__main__":
    main()
